### ISSUE TITLE
Fix download for toptoonplus.com

### ISSUE THREAD

**Issue by D0unut** [HDoujinDownloader/HDoujinDownloader#132]
I tried to download chapters for some series there, but the status went from "Grabbing pages" to "Completed" without actually downloading anything.

**Comment by HDoujinDownloader** [comment]
Have you added a bearer token by following the instructions [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/Downloading-from-Toptoon-Plus)? By adding your token, you'll be able to download mature content and content tied to your account.

If you've done this previously, it could be that your token has expired. You can verify this by looking for the following line in the log viewer (**_Tools > Log Viewer_**) when attempting to download:

    20:08:08 chapter gra [x] System.Net.WebException: The remote server returned an error: (463) Unknown.

Update your bearer token, and that should resolve the issue.

**Comment by rs3mk** [comment]
![toptoonplus](https://user-images.githubusercontent.com/19628943/181734704-5d8261e4-033c-455f-99ac-0e9e8e201832.png)

**Comment by D0unut** [comment]
Thanks for letting me know that you can get the token from the Application tab as well, I was getting it from the Network tab.
That aside, it still doesn't work, I tried it multiple times but alas, one second it says that it grabs the page but the next second it says completed without actually accomplishing anything. I was using it for a couple of months and everything was great, but on the same day as I wrote about this issue here it ceased to work

**Comment by HDoujinDownloader** [comment]
You're right, copying in the token string doesn't seem to work anymore. I'm moving further discussion on this issue to #222.
